booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    
    # Аутентификация
    path('register/', views.RegistrationTypeView.as_view(), name='register_type'),
    path('register/user/', views.UserRegistrationView.as_view(), name='register_user'),
    path('register/organization/', views.OrganizationRegistrationView.as_view(), name='register_organization'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
    # Личный кабинет
    path('profile/', views.ProfileView.as_view(), name='profile'),
    
    # Панель организации
    path('organization/', views.OrganizationPanelView.as_view(), name='organization_panel'),
    path('organization/hotels/create/', views.HotelCreateView.as_view(), name='hotel_create'),
    path('organization/hotels/<int:pk>/edit/', views.HotelUpdateView.as_view(), name='hotel_edit'),
    path('organization/rooms/create/', views.RoomCreateView.as_view(), name='room_create'),
    path('organization/rooms/<int:pk>/edit/', views.RoomUpdateView.as_view(), name='room_edit'),
    
    # Номера
    path('rooms/', views.RoomListView.as_view(), name='rooms'),
    path('rooms/<int:pk>/', views.RoomDetailView.as_view(), name='room_detail'),
    path('rooms/<int:room_id>/check-availability/', views.check_room_availability, name='check_room_availability'),
    
    # Гости
    path('guests/', views.GuestListView.as_view(), name='guests'),
    path('guests/create/', views.GuestCreateView.as_view(), name='guest_create'),
    path('guests/<int:pk>/', views.GuestDetailView.as_view(), name='guest_detail'),
    
    # Бронирования
    path('bookings/', views.BookingListView.as_view(), name='bookings'),
    path('bookings/create/', views.BookingCreateView.as_view(), name='booking_create'),
    path('bookings/<int:pk>/', views.BookingDetailView.as_view(), name='booking_detail'),
    
    # Контакты
    path('contact/', views.ContactView.as_view(), name='contact'),
]

hotel_booking/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.static import serve as static_serve
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('booking.api_urls')),
    path('', include('booking.urls')),
    # Swagger UI для Booking Service
    path(
        'swagger/',
        TemplateView.as_view(template_name='swagger.html'),
        name='booking-swagger-ui',
    ),
    # Отдача OpenAPI-спецификации для Swagger UI
    re_path(
        r'^swagger/openapi\.yaml$',
        static_serve,
        {
            'document_root': os.path.join(settings.BASE_DIR, 'docs'),
            'path': 'openapi-booking-service.yaml',
        },
        name='booking-openapi-yaml',
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from .models import Room, Guest, Booking, Hotel, UserProfile
from .forms import BookingForm, GuestForm, UserRegistrationForm, OrganizationRegistrationForm, UserProfileForm, HotelForm, RoomForm


class HomeView(TemplateView):
    """Главная страница"""
    template_name = 'booking/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rooms_count'] = Room.objects.count()
        context['guests_count'] = Guest.objects.count()
        context['bookings_count'] = Booking.objects.count()
        context['available_rooms'] = Room.objects.select_related('hotel').all()[:3]
        return context


class RegistrationTypeView(TemplateView):
    """Выбор типа регистрации"""
    template_name = 'booking/registration_type.html'


class UserRegistrationView(CreateView):
    """Регистрация пользователя"""
    form_class = UserRegistrationForm
    template_name = 'booking/register_user.html'
    success_url = reverse_lazy('booking:home')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        messages.success(self.request, 'Регистрация успешна! Добро пожаловать!')
        return response


class OrganizationRegistrationView(CreateView):
    """Регистрация организации"""
    form_class = OrganizationRegistrationForm
    template_name = 'booking/register_organization.html'
    success_url = reverse_lazy('booking:organization_panel')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        messages.success(self.request, 'Организация успешно зарегистрирована!')
        return response


@require_http_methods(["GET", "POST"])
def login_view(request):
    """Вход в систему"""
    if request.method == 'POST':
        from django.contrib.auth import authenticate
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f'Добро пожаловать, {user.username}!')
            if hasattr(user, 'profile') and user.profile.is_organization:
                return redirect('booking:organization_panel')
            return redirect('booking:home')
        else:
            messages.error(request, 'Неверное имя пользователя или пароль')
    return render(request, 'booking/login.html')


@login_required
def logout_view(request):
    """Выход из системы"""
    logout(request)
    messages.success(request, 'Вы успешно вышли из системы')
    return redirect('booking:home')


class ProfileView(LoginRequiredMixin, UpdateView):
    """Личный кабинет пользователя"""
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'booking/profile.html'
    success_url = reverse_lazy('booking:profile')
    
    def get_object(self):
        profile, created = UserProfile.objects.get_or_create(user=self.request.user)
        return profile
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_bookings'] = Booking.objects.filter(user=self.request.user).order_by('-check_in_date')[:10]
        return context
    
    def form_valid(self, form):
        messages.success(self.request, 'Профиль успешно обновлен!')
        return super().form_valid(form)


class OrganizationPanelView(LoginRequiredMixin, TemplateView):
    """Панель организации"""
    template_name = 'booking/organization_panel.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(request.user, 'profile') or not request.user.profile.is_organization:
            messages.error(request, 'Доступ запрещен. Только для организаций.')
            return redirect('booking:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hotels'] = Hotel.objects.filter(owner=self.request.user)
        context['rooms'] = Room.objects.filter(hotel__owner=self.request.user)
        context['bookings'] = Booking.objects.filter(room__hotel__owner=self.request.user).order_by('-check_in_date')[:10]
        return context


class HotelCreateView(LoginRequiredMixin, CreateView):
    """Создание отеля"""
    model = Hotel
    form_class = HotelForm
    template_name = 'booking/hotel_form.html'
    success_url = reverse_lazy('booking:organization_panel')
    
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(request.user, 'profile') or not request.user.profile.is_organization:
            messages.error(request, 'Доступ запрещен. Только для организаций.')
            return redirect('booking:home')
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        hotel = form.save(commit=False)
        hotel.owner = self.request.user
        hotel.save()
        messages.success(self.request, 'Отель успешно создан!')
        return redirect(self.success_url)


class HotelUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование отеля"""
    model = Hotel
    form_class = HotelForm
    template_name = 'booking/hotel_form.html'
    success_url = reverse_lazy('booking:organization_panel')
    
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(request.user, 'profile') or not request.user.profile.is_organization:
            messages.error(request, 'Доступ запрещен.')
            return redirect('booking:home')
        hotel = self.get_object()
        if hotel.owner != request.user:
            messages.error(request, 'У вас нет прав для редактирования этого отеля.')
            return redirect('booking:organization_panel')
        return super().dispatch(request, *args, **kwargs)


class RoomCreateView(LoginRequiredMixin, CreateView):
    """Создание номера"""
    model = Room
    form_class = RoomForm
    template_name = 'booking/room_form.html'
    success_url = reverse_lazy('booking:organization_panel')
    
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(request.user, 'profile') or not request.user.profile.is_organization:
            messages.error(request, 'Доступ запрещен. Только для организаций.')
            return redirect('booking:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = kwargs.get('initial', {})
        hotel_id = self.request.GET.get('hotel')
        if hotel_id:
            try:
                hotel = Hotel.objects.get(pk=hotel_id, owner=self.request.user)
                kwargs['initial']['hotel'] = hotel
            except Hotel.DoesNotExist:
                pass
        return kwargs
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['hotel'].queryset = Hotel.objects.filter(owner=self.request.user)
        return form
    
    def form_valid(self, form):
        messages.success(self.request, 'Номер успешно создан!')
        return super().form_valid(form)


class RoomUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование номера"""
    model = Room
    form_class = RoomForm
    template_name = 'booking/room_form.html'
    success_url = reverse_lazy('booking:organization_panel')
    
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(request.user, 'profile') or not request.user.profile.is_organization:
            messages.error(request, 'Доступ запрещен.')
            return redirect('booking:home')
        room = self.get_object()
        if room.hotel.owner != request.user:
            messages.error(request, 'У вас нет прав для редактирования этого номера.')
            return redirect('booking:organization_panel')
        return super().dispatch(request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['hotel'].queryset = Hotel.objects.filter(owner=self.request.user)
        return form


class RoomListView(ListView):
    """Список номеров"""
    model = Room
    template_name = 'booking/rooms.html'
    context_object_name = 'rooms'
    paginate_by = 9
    
    def get_queryset(self):
        queryset = Room.objects.select_related('hotel').all()
        room_type = self.request.GET.get('type')
        hotel_id = self.request.GET.get('hotel')
        if room_type:
            queryset = queryset.filter(type_name__icontains=room_type)
        if hotel_id:
            queryset = queryset.filter(hotel_id=hotel_id)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['room_types'] = Room.objects.values_list('type_name', flat=True).distinct()
        context['hotels'] = Hotel.objects.all()
        return context


class RoomDetailView(DetailView):
    """Детальная информация о номере"""
    model = Room
    template_name = 'booking/room_detail.html'
    context_object_name = 'room'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

templates/booking/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Система бронирования отелей{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'booking:home' %}">
                <i class="bi bi-building-fill"></i> <strong>HotelBooking</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'booking:home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'booking:rooms' %}">Номера</a>
                    </li>
                    {% if user.is_authenticated %}
                        {% if user.profile.is_organization %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'booking:organization_panel' %}">Панель организации</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'booking:bookings' %}">Мои бронирования</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'booking:profile' %}">Личный кабинет</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'booking:logout' %}">Выход</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'booking:login' %}">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'booking:register_type' %}">Регистрация</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'booking:contact' %}">Контакты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container my-5 fade-in">
        {% if messages %}
            <div class="mb-4">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show shadow-md" role="alert">
                        <i class="bi bi-{% if message.tags == 'success' %}check-circle{% elif message.tags == 'error' or message.tags == 'danger' %}exclamation-triangle{% elif message.tags == 'warning' %}exclamation-circle{% else %}info-circle{% endif %} me-2"></i>
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}{% endblock %}
    </main>

    <footer class="py-4 mt-5">
        <div class="container text-center">
            <p class="mb-0">&copy; 2025 Система бронирования отелей. Все права защищены.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/booking/booking_detail.html
{% extends 'booking/base.html' %}

{% block title %}Бронирование #{{ booking.booking_id }} - Система бронирования отелей{% endblock %}

{% block content %}
<div class="row fade-in-up">
    <div class="col-md-8">
        <div class="mb-4">
            <h1 class="fw-bold mb-2">
                <i class="bi bi-calendar-check text-primary me-2"></i>Бронирование #{{ booking.booking_id }}
            </h1>
            <p class="text-muted">Детальная информация о бронировании</p>
        </div>
        
        <div class="card shadow-lg border-0 mb-4">
            <div class="card-header">
                <h5 class="mb-0 fw-bold">
                    <i class="bi bi-person me-2"></i>Информация о госте
                </h5>
            </div>
            <div class="card-body">
                <table class="table table-borderless mb-0">
            <tr>
                <th>Гость:</th>
                <td>
                    <a href="{% url 'booking:guest_detail' booking.guest.pk %}">
                        {{ booking.guest.full_name }}
                    </a>
                </td>
            </tr>
            <tr>
                <th>Телефон:</th>
                <td>{{ booking.guest.phone }}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{ booking.guest.email|default:"—" }}</td>
            </tr>
                </table>
            </div>
        </div>
        
        <div class="card shadow-lg border-0 mb-4">
            <div class="card-header">
                <h5 class="mb-0 fw-bold">
                    <i class="bi bi-door-open me-2"></i>Информация о номере
                </h5>
            </div>
            <div class="card-body">
                <table class="table table-borderless mb-0">
            <tr>
                <th>Отель:</th>
                <td>{{ booking.room.hotel.name }}</td>
            </tr>
            <tr>
                <th>Номер:</th>
                <td>
                    <a href="{% url 'booking:room_detail' booking.room.pk %}">
                        {{ booking.room.name }} ({{ booking.room.number }})
                    </a>
                </td>
            </tr>
            <tr>
                <th>Тип:</th>
                <td>{{ booking.room.type_name }}</td>
            </tr>
            <tr>
                <th>Цена за ночь:</th>
                <td>{{ booking.room.price_per_night }} ₽</td>
            </tr>
                </table>
            </div>
        </div>
        
        <div class="card shadow-lg border-0 mb-4">
            <div class="card-header">
                <h5 class="mb-0 fw-bold">
                    <i class="bi bi-info-circle me-2"></i>Детали бронирования
                </h5>
            </div>
            <div class="card-body">
                <table class="table table-borderless mb-0">
            <tr>
                <th>Дата заезда:</th>
                <td>{{ booking.check_in_date|date:"d.m.Y" }}</td>
            </tr>
            <tr>
                <th>Дата выезда:</th>
                <td>{{ booking.check_out_date|date:"d.m.Y" }}</td>
            </tr>
            <tr>
                <th>Количество взрослых:</th>
                <td>{{ booking.adults_count }}</td>
            </tr>
            <tr>
                <th>Количество детей:</th>
                <td>{{ booking.children_count }}</td>
            </tr>
            <tr>
                <th>Стоимость:</th>
                <td><strong class="text-success">{{ booking.total_price }} ₽</strong></td>
            </tr>
            {% if booking.special_requests %}
            <tr>
                <th>Пожелания:</th>
                <td>{{ booking.special_requests|linebreaks }}</td>
            </tr>
            {% endif %}
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card shadow-lg border-0 mb-4">
            <div class="card-header">
                <h5 class="mb-0 fw-bold">
                    <i class="bi bi-info-circle me-2"></i>Дополнительная информация
                </h5>
            </div>
            <div class="card-body">
                <div class="mb-3 pb-3 border-bottom">
                    <p class="text-muted mb-1 small">ID бронирования</p>
                    <p class="mb-0 fw-bold">#{{ booking.booking_id }}</p>
                </div>
                <div class="mb-3 pb-3 border-bottom">
                    <p class="text-muted mb-1 small">Создано</p>
                    <p class="mb-0">{{ booking.created_at|date:"d.m.Y H:i" }}</p>
                </div>
                <div class="mb-0">
                    <p class="text-muted mb-1 small">Обновлено</p>
                    <p class="mb-0">{{ booking.updated_at|date:"d.m.Y H:i" }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-12">
        <a href="{% url 'booking:bookings' %}" class="btn btn-secondary">
            <i class="bi bi-arrow-left me-2"></i>Назад к списку бронирований
        </a>
    </div>
</div>
{% endblock %}

templates/booking/organization_panel.html
{% extends 'booking/base.html' %}

{% block title %}Панель организации - Система бронирования отелей{% endblock %}

{% block content %}
<div class="row mb-5">
    <div class="col-12 text-center">
        <h1 class="display-4 fw-bold mb-3">
            <span style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
                Панель организации
            </span>
        </h1>
        <p class="lead text-muted">Управление отелями и номерами</p>
    </div>
</div>

<div class="row mb-5">
    <div class="col-md-4 mb-4">
        <div class="card text-center border-0 shadow-lg h-100">
            <div class="card-body p-4">
                <div class="mb-3">
                    <div class="d-inline-block p-4 rounded-circle" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
                        <i class="bi bi-building display-4 text-white"></i>
                    </div>
                </div>
                <h2 class="display-4 fw-bold mb-2" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">{{ hotels.count }}</h2>
                <p class="text-muted fs-5 mb-0">Отелей</p>
            </div>
        </div>
    </div>
    <div class="col-md-4 mb-4">
        <div class="card text-center border-0 shadow-lg h-100">
            <div class="card-body p-4">
                <div class="mb-3">
                    <div class="d-inline-block p-4 rounded-circle" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);">
                        <i class="bi bi-door-open display-4 text-white"></i>
                    </div>
                </div>
                <h2 class="display-4 fw-bold mb-2" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">{{ rooms.count }}</h2>
                <p class="text-muted fs-5 mb-0">Номеров</p>
            </div>
        </div>
    </div>
    <div class="col-md-4 mb-4">
        <div class="card text-center border-0 shadow-lg h-100">
            <div class="card-body p-4">
                <div class="mb-3">
                    <div class="d-inline-block p-4 rounded-circle" style="background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);">
                        <i class="bi bi-calendar-check display-4 text-white"></i>
                    </div>
                </div>
                <h2 class="display-4 fw-bold mb-2" style="background: linear-gradient(135deg, #fa709a 0%, #fee140 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">{{ bookings.count }}</h2>
                <p class="text-muted fs-5 mb-0">Бронирований</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 mb-4">
        <div class="card border-0 shadow-lg">
            <div class="card-header d-flex justify-content-between align-items-center" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
                <h5 class="mb-0 text-white"><i class="bi bi-building"></i> Мои отели</h5>
                <a href="{% url 'booking:hotel_create' %}" class="btn btn-light btn-sm">
                    <i class="bi bi-plus-circle"></i> Добавить отель
                </a>
            </div>
            <div class="card-body">
                {% if hotels %}
                <div class="list-group">
                    {% for hotel in hotels %}
                    <div class="list-group-item">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <h6 class="mb-1">{{ hotel.name }}</h6>
                                <p class="mb-1 text-muted small">{{ hotel.address|truncatewords:10 }}</p>
                            </div>
                            <div>
                                <a href="{% url 'booking:hotel_edit' hotel.pk %}" class="btn btn-sm btn-outline-primary">
                                    <i class="bi bi-pencil"></i> Редактировать
                                </a>
                                <a href="{% url 'booking:room_create' %}?hotel={{ hotel.pk }}" class="btn btn-sm btn-outline-success">
                                    <i class="bi bi-plus"></i> Добавить номер
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <p class="text-muted">У вас пока нет отелей. <a href="{% url 'booking:hotel_create' %}">Создать первый отель</a></p>
                {% endif %}
            </div>
        </div>
    </div>
    
    <div class="col-md-6 mb-4">
        <div class="card border-0 shadow-lg">
            <div class="card-header" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);">
                <h5 class="mb-0 text-white"><i class="bi bi-calendar-check"></i> Последние бронирования</h5>
            </div>
            <div class="card-body">
                {% if bookings %}
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>Гость</th>
                                <th>Номер</th>
                                <th>Даты</th>
                                <th>Стоимость</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for booking in bookings %}
                            <tr>
                                <td>{{ booking.guest.full_name }}</td>
                                <td>{{ booking.room.number }}</td>
                                <td>{{ booking.check_in_date|date:"d.m" }} - {{ booking.check_out_date|date:"d.m" }}</td>
                                <td>{{ booking.total_price }} ₽</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <a href="{% url 'booking:bookings' %}" class="btn btn-sm btn-outline-primary">Все бронирования</a>
                {% else %}
                <p class="text-muted">Пока нет бронирований</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card border-0 shadow-lg">
            <div class="card-header" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
                <h5 class="mb-0 text-white"><i class="bi bi-door-open"></i> Все номера</h5>
            </div>
            <div class="card-body">
                {% if rooms %}
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Отель</th>
                                <th>Номер</th>
                                <th>Название</th>
                                <th>Тип</th>
                                <th>Цена за ночь</th>
                                <th>Действия</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for room in rooms %}
                            <tr>
                                <td>{{ room.hotel.name }}</td>
                                <td>{{ room.number }}</td>
                                <td>{{ room.name }}</td>
                                <td>{{ room.type_name }}</td>
                                <td><strong>{{ room.price_per_night }} ₽</strong></td>
                                <td>
                                    <a href="{% url 'booking:room_edit' room.pk %}" class="btn btn-sm btn-primary">
                                        <i class="bi bi-pencil"></i> Редактировать
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <p class="text-muted">У вас пока нет номеров</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}